yatube/posts/urls.py
from django.urls import path


from . import views
app_name = 'Posts'


urlpatterns = [
    path('', views.index, name='index'),
    path('group/', views.group_posts, name='group_posts'),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import path, include
"""yatube URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('', include('posts.urls', namespace='Posts')),
    path('admin/', admin.site.urls),
]

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model
# Create your models here.

User = get_user_model()


class Posts(models.Model):
    text = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE,
                               related_name='posts')

yatube/posts/views.py
from django.shortcuts import render
from django.http import HttpResponse
# Create your views here.


def index(request):
    template = 'posts/index.html'
    text = 'Это главная страница проекта Yatube'
    context = {
        'text': text,
    }
    return render(request, template, context)


def group_posts(request):
    template = 'posts/group_list.html'
    text = 'ГЗдесь будет информация о группах проекта Yatube'
    context = {
        'text': text,
    }
    return render(request, template, context)

yatube/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
          Последние обновления
        {% endblock %}
    </title>
</head>
<body>
<header>
    {% include 'includes/header.html' %}
</header>
<main>
    {% block content %}
      Контент не подвезли
    {% endblock content %}
</main>
<footer>
    {% include 'includes/footer.html' %}
</footer>
</body>
</html>

yatube/templates/includes/footer.html
<footer class="page-footer font-small blue border-top">
    <div class="footer-copyright text-center py-3">© 2020 Copyright
        <p><span style="color:red">Ya</span>tube</p>
    </div>
</footer>

yatube/templates/includes/header.html
{% load static %}
<header>
      <!-- Использованы классы бустрапа для создания типовой навигации с логотипом -->
      <!-- В дальнейшем тут будет создано полноценное меню -->
    <nav class="navbar navbar-light" style="background-color: lightskyblue">
        <div class="container">
            <a class="navbar-brand" href="{% url 'Posts:index' %}">
                <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
            <!-- тег span используется для добавления нужных стилей отдельным участкам текста -->
                <span style="color:red">Ya</span>tube
            </a>
        </div>
    </nav>
</header>

yatube/templates/posts/group_list.html
<!DOCTYPE html> <!-- Используется html 5 версии -->
{% extends 'base.html' %}
<html lang="ru"> <!-- Язык сайта - русский -->
  <head>    
    <meta charset="utf-8"> <!-- Кодировка сайта -->
    <!-- Сайт готов работать с мобильными устройствами -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Загружаем фав-иконки -->
    <link rel="icon" href="img/fav/fav.ico" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="../includes/img/fav/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="../includes/img/fav/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="../includes/img/fav/favicon-16x16.png">
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">
    <!-- Подключен файл со стандартными стилями бустрап -->
    <link rel="stylesheet" href="../includes/css/bootstrap.min.css">
    <title>
      {% block title %}
        Лев Толстой – зеркало русской революции.
      {% endblock title %}
    </title>
  </head>
  <body>
    <main>
      {% block content %}
        {{ text }}
      {% endblock content %}
    </main>

  </body>
</html>

yatube/templates/posts/index.html
<!DOCTYPE html> <!-- Используется html 5 версии -->
{% extends 'base.html' %}
{% load static %}
<html lang="ru"> <!-- Язык сайта - русский -->
  <head>
    <meta charset="utf-8"> <!-- Кодировка сайта -->
    <!-- Сайт готов работать с мобильными устройствами -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Загружаем фав-иконки -->
    <link rel="icon" href="img/fav/fav.ico" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="../includes/img/fav/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="../includes/img/fav/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="../includes/img/fav/favicon-16x16.png">
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">
    <!-- Подключен файл со стандартными стилями бустрап -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>
      {% block title %}
        Последние обновления на сайте
      {% endblock title %}
    </title>
  </head>
  <body>
    <main>
      {% block content %}
        {{ text }}
      {% endblock content %}
    </main>
  </body>
</html>